version: "3.8"

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=ap-northeast-2
      - DATA_DIR=/tmp/localstack/data

  aws-cli:
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.MockingAWSS3
    container_name: aws-cli
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-northeast-2
    depends_on:
      - localstack
